version: '3'
services:
  rwdb:
    image: mysql:oracle
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
      MYSQL_DATABASE: realworld # for database creation automatically
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql:rw"
